version: "3"

# Source: https://github.com/pi-hole/docker-pi-hole

services:
  nginx-proxy:
    env_file: .env
    image: nginxproxy/nginx-proxy:latest
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pihole.${MY_DOMAIN}
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always

  pihole:
    env_file: .env
    hostname: pi.hole
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "${PH_HTTP_HOST_PORT}:80/tcp"
      - "${PH_DNS_HOST_PORT}:53/tcp"
      - "${PH_DNS_HOST_PORT}:53/udp"
    environment:
      ServerIP: ${HOST_IP}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.${MY_DOMAIN}
      VIRTUAL_PORT: 80
    volumes:
      - '${CONFIG_ROOT}/etc/pihole/:/etc/pihole/'
      - '${CONFIG_ROOT}/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    extra_hosts:
      - "pihole pihole.${MY_DOMAIN}:${HOST_IP}"
      - "${MY_ROUTER}"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
